apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-kube-app
  template:
    metadata:
      labels:
        app: my-kube-app
    spec:
      containers:
      - name: my-kube-app
        image: yourusername/my-kube-app:1.0  # Replace with your Dockerhub username and image tag
        ports:
        - containerPort: 5000
